version: "3.8"

services:
  postgres:
    image: postgres:18-alpine
    container_name: ngantri-postgres
    environment:
      POSTGRES_DB: ngantri
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - ngantri-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ngantri-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ngantri.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ngantri-network
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local

networks:
  ngantri-network:
    driver: bridge
